### ISSUE TITLE
items not autocrafted in ME interface when those items were used in autocraft

### ISSUE THREAD

**Issue by PandaGamersHDNL** [PrototypeTrousers/Applied-Energistics-2#103]
**Describe the bug**

when crafting other items by autocraft the items in an interface with a storage bus are not replenished by the system. the system has enough channels, resources and crafting memory to deal with the recipe.

**To Reproduce**

create a system with storage and some crafting thing. i used a molecular assembler with a crafting table pattern and a crafting card pattern. then create a storage bus + interface combo with a crafting card and 10 crafting tables. it seems to work fine at first but if the 10 crafting tables have been made, request a couple of crafting cards. the cards will be crafted successfully and with enough wood in the system the crafting tables are NOT restocked.

**Expected behavior**

the system should start crafting the crafting tables to refill it's buffer. pulling out the items by hand from the terminal does initiate the interface to stock up.

**Additional context**

setup: 
![Screenshot 2022-05-11 075404](https://user-images.githubusercontent.com/13972484/167778800-07e09b5f-430b-4a3d-bab1-ea3a6b27786a.png)

**Environment**

done in single player with just:
Just enough items: 4.15.0.293
also happening in the nomifactory mod pack:
single player and multiplayer

- Minecraft Version: 
- AE2 Version: appliedenergistics2-rv6-stable-7-extended_life-v49ac
- Forge Version: 14.23.5.2860
- MC: 1.12.2

**Comment by PrototypeTrousers** [comment]
please update to the latest version, this bug was fixed in v50b
