### ISSUE TITLE
Crash on attaching ME Drive (block) to ME interface of a seperate network through an import bus on interface.

### ISSUE THREAD

**Issue by AlfarelSynthesis** [PrototypeTrousers/Applied-Energistics-2#104]
**Describe the bug**
Most recent version on curse. Playing GCP with updated mods, etc.
ME Interface's system is has two storage buses connected to drawers. At least one has multiple 32x storage multipliers. ME Drive is full of drives, not all in use, about half 16k half 4k.

**To Reproduce**
Power an ME Drive full of drives (16k should work), containing items. Power a separate ME System with an interface and two drawers, with 32x storage upgrades, with a few thousand blocks each inside. Connect import bus to ME Interface. Connect ME Drive to import bus with ME cables. Might also be pertinent that I had a completely empty ME Drive (block) attacked to the ME Interface system. <-Also crashes with just an import bus into an interface.

**Expected behavior**
No crash, at least.

**Additional context**
[crash-2022-05-11_20.15.02-server.txt](https://github.com/PrototypeTrousers/Applied-Energistics-2/files/8674112/crash-2022-05-11_20.15.02-server.txt)

**Environment**
Above
Singleplayer. No Vanillafix, censored version 5.2. Spark version 1.5.2. 

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7-extended_life-v0.52.5
- Forge Version: 14.23.5.2860

**Comment by AlfarelSynthesis** [comment]
![2022-05-12_18 57 31](https://user-images.githubusercontent.com/104072649/168180760-17f73198-a59b-498c-b7db-ce2b3ffbe318.png)
Managed to setblock my way out of the crash, have a version of the save with the crash setup still there. the ME cable and attached import bus were in between the blocks shown.

**Comment by AlfarelSynthesis** [comment]
[crash-2022-05-12_19.13.35-server.txt](https://github.com/PrototypeTrousers/Applied-Energistics-2/files/8683023/crash-2022-05-12_19.13.35-server.txt)
Yeah, it's definitely the import bus. Here's another log. Bus attached to interface from a single system, cable -> import bus -> interface.

**Comment by PrototypeTrousers** [comment]
This issues is due to local WIP changes of .6 that made to the jar.
Either downgrade to .4 or update to .6 ( and leave a feedback of the interface on interface blocking mode)
