### ISSUE TITLE
Bi-Directional/Export Only Storage Bus on Interface with Crafting card won't send crafting requests to Autocrafting system

### ISSUE THREAD

**Issue by ScorpioRage** [PrototypeTrousers/Applied-Energistics-2#106]
**Describe the issue**
Expected: Interface would send crafting requests to system to keep specified stock, regardless of being able to see its own inventory on the system.
Actual: The interface is not sending Autocrafting requests even though it has a crafting card, and it doesn't have the correct stock of items.
Linked video demonstrating the problem: 
https://drive.google.com/file/d/1G3-fxKXVD00JbJvomBAC75nSPmYTPyT2/view?usp=sharing

**Environment**
Forge Minecraft 1.12.2
Mods used:
![image](https://user-images.githubusercontent.com/6668983/168460766-376c389e-1001-49e3-a73e-fb5e57b82e50.png)

**Comment by PrototypeTrousers** [comment]
fixed in 0.52.7
