### ISSUE TITLE
Ask and you shall receive!

### ISSUE THREAD

**Issue by lesdmark** [PrototypeTrousers/Applied-Energistics-2#11]
**Describe the bug**

30d
**To Reproduce**

Look up a recipe in JEI click it into the crafting terminal. Voila! the ingredients are there whether you have them or not.

**Expected behavior**

Not dupe like crazy!

**Additional context**

**Environment**

Server MP I am admin as well if that makes a difference, JEI version 4,15,0,297

- Minecraft Version: 1.12
- AE2 Version: 30d
- Forge Version: 14.23.5.2847

**Comment by lesdmark** [comment]
As a side note, It does deduct the ingredients from you AE2 inventory if you actually have them.

**Comment by PrototypeTrousers** [comment]
fixed in 30e
