### ISSUE TITLE
Crash and crafting calculation slowness since v34 update

### ISSUE THREAD

**Issue by Caedis** [PrototypeTrousers/Applied-Energistics-2#12]
**Describe the bug**
Since the upgrade to v34, the crafting calculation slowed way down and even caused a server crash (only into HV, so probably crazier in higher voltages)

**To Reproduce**
Slowness was shown anytime I was starting a new autocraft (at the time, I was making 3 HV Macerators, a Drawer Controller and a Drawer Slave)

**Expected behavior**
No slowness and no crash

**Additional context**
[Gist Crashlog](https://gist.github.com/Caedis/6f5157cdc698f36ad1b3e825cc1ca902)

**Environment**
Omnifactory dev build: fa485e6

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7.omni-fixes-v34.jar
- Forge Version: 14.23.5.2847

**Comment by Caedis** [comment]
Downgrading to v33b to see if the issues go away.

**Comment by Caedis** [comment]
Downgrading to v33b brings back the normal swiftness of the crafting calculations and have not had a crash

**Comment by Caedis** [comment]
Definitely no crafting calculation slowdown on c3b1dea

**Comment by PrototypeTrousers** [comment]
Sorry about that, i committed an unfinished branch on top of v34. Should be back to normal on v34b

**Comment by Caedis** [comment]
Cool, i'll do some testing

**Comment by Caedis** [comment]
Crafting calculation is still much slower than v32b

**Comment by Caedis** [comment]
Update for anyone who reads this, solution was the disable substitutions on crafting patterns. After doing that, every crafting plan calc is instant.
