### ISSUE TITLE
Reward players respecting channels when `Channels` feature is disabled

### ISSUE THREAD

**Issue by slava110** [PrototypeTrousers/Applied-Energistics-2#125]
**Describe the feature**
In newer version of AE you can have infinite channels but if you still respect channel rules you will have significantly lower energy consumption. I think something like that could be implemented in 1.12
*Also thought about other benefits for players respecting channels but I cannot imagine anything except energy consumption. Maybe you can?*
![изображение](https://user-images.githubusercontent.com/26705162/183245964-03973d21-1176-4fcd-9785-0f89ffb42bb1.png)

**Reasons why it should be considered**
I'm playing with my friend who really likes all this channel stuff and thinks it's interesting. For me tho it is frustrating to play with channels. So I thought it would be cool if I will be able to make my ME network without channels and he will be able to make his network with channels + also will have some benefits from that so it will be kinda fair

**Additional Context**
You can add lower consumption ratio as config option

**Comment by PrototypeTrousers** [comment]
implemented in 7996c44075af1521859196ddc2b02efcc62f497e
Now having a ME controller on your network gives you a energy discount.

**Comment by slava110** [comment]
I'm using `v0.53.4` and this feature doesn't work for me. Was it tested? Am I doing something wrong
![2022-08-29_10 16 56](https://user-images.githubusercontent.com/26705162/187154172-1155eed6-f00c-42bb-8cf8-b5784ce4e37f.png)
![2022-08-29_10 17 00](https://user-images.githubusercontent.com/26705162/187154176-b4aaf398-75ff-4646-a570-965c7196d1f0.png)
?
