### ISSUE TITLE
Crash when storage drawers is not present

### ISSUE THREAD

**Issue by Jimmy469** [PrototypeTrousers/Applied-Energistics-2#13]
If installed in a modpack without storage drawers present, a server crash is encountered when an interface is connected to a non-AE2 device. In the crash log attached, the crash occurs with a TechReborn machine.

Using version 34d

**To Reproduce**
Using modpack Nuclear Earth: Reirradiated (although I expect any pack without storagedrawers would work), connect an interface to a machine, then open the interface terminal. Crash occurs upon opening interface terminal.

**Expected behavior**
No crash?

**Additional context**
[crash-2021-04-09_01.03.55-server.txt](https://github.com/PrototypeTrousers/Applied-Energistics-2/files/6284140/crash-2021-04-09_01.03.55-server.txt)

**Environment**
Modpack: Nuclear Earth: Reirradiated 2.0.8, with pants ae2 added, regular ae2 and jee removed.
34d

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7.omni-fixes-v34d
- Forge Version: forge-1.12.2-14.23.5.2854

**Comment by PrototypeTrousers** [comment]
i've bundled the api; as i did not crash with the steps mentioned above, please confirm if v35 fixes this

**Comment by Jimmy469** [comment]
Can confirm it does not immediately crash with v35. If further issues arise related to this, I'll reopen the issue with further info, but at a glance things seem to be a-ok.
