### ISSUE TITLE
JEI Monitor bug

### ISSUE THREAD

**Issue by dimon7147** [PrototypeTrousers/Applied-Energistics-2#132]
**Describe the bug**
When using the monitor in a long style, blank bars appear at the top of the JEI. There are none when using the normal mode.

**To Reproduce**
Install v0.53.3 and switch monitor mode to long.

**Expected behavior**
Blank bars will appear at the top of the JEI

**Additional context**
![image](https://user-images.githubusercontent.com/20266345/186975628-9c89adf1-5f7b-4282-b6bb-4fadc30fff1c.png)

**Environment**
The problem appeared after updating the mod from v0.52.10 to v0.53.3

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7-extended_life-v0.53.3.
- Forge Version: 14.23.5.2860

**Comment by PrototypeTrousers** [comment]
v0.53.4 should fix this and should be up on curseforge shortly
