### ISSUE TITLE
Shift clicking the down arrow in the pattern terminal creates an encoded pattern with no recipe

### ISSUE THREAD

**Issue by Renno231** [PrototypeTrousers/Applied-Energistics-2#142]
**Describe the bug**
In version v0.53.5 (in the 1.12.2 modpack) when shift clicking the button to encode a pattern with the recipe in the pattern terminal its supposed to encode it as normal and then insert said pattern into the players inventory, but instead it encodes a blank recipe on the pattern and puts it into the players inventory.

**To Reproduce**
Try to make an encoded pattern the normal way except hold shift when clicking the encode (down arrow) button.

**Expected behavior**
Should place a pattern with the recipe in the pattern terminal into the players inventory

**Environment**
MP, 1.12.2 pack

- Minecraft Version: 
- AE2 Version: 0.53.5
- Forge Version: 14.23.5.2860

**Comment by Renno231** [comment]
It also appears to happen even normally when not holding shift, I have to (every time) click the button twice otherwise it encodes a blank pattern.

**Comment by Renno231** [comment]
![2022-09-17_16 03 55](https://user-images.githubusercontent.com/75190549/190876385-6ac887d8-0bf4-4e2e-9666-eb6b2c6f1e94.png)
![2022-09-17_16 03 57](https://user-images.githubusercontent.com/75190549/190876386-136deb6e-1220-4f2a-8862-77763398c841.png)
![2022-09-17_16 03 59](https://user-images.githubusercontent.com/75190549/190876388-eaeb1d90-73a2-45fc-b240-ad427f05a626.png)

**Comment by YoungOnionMC** [comment]
This was already fixed in 1ed6548

**Comment by xJon** [comment]
If this is referring to https://github.com/xJon/The-1.12.2-Pack, I'll update the pack with the new mod version in the next couple of days
