### ISSUE TITLE
Crash on starting large craft

### ISSUE THREAD

**Issue by Caedis** [PrototypeTrousers/Applied-Energistics-2#15]
**Describe the bug**
After starting a large auto-craft for 8 sets of chaos shards, I was kicked with a "Server Closed" error and decided to check my server's logs and got the errors shown under Additional Context. Server crashes on restart as it tries to continue with the craft.

**To Reproduce**
Started a craft for 8 sets of chaos shards

**Expected behavior**
To start the craft without crafting

**Additional context**
[Crash after starting autocraft](https://gist.github.com/Caedis/76b71a44e285daef2d27faf509a71652)  
[Crash immediately after server restarted](https://gist.github.com/Caedis/c8dd086d468d0df8e752e5544088f0a8) (probably same error)

**Environment**
- Host: Docker Container (https://hub.docker.com/r/itzg/minecraft-server) on Arch Linux
- Minecraft Version: 1.12.2
- AE2 Version: v38
- Forge Version: 14.23.5.2847

**Comment by Caedis** [comment]
As a hold over, swapping back to v37 and everything seems to be fine.

**Comment by PrototypeTrousers** [comment]
should be fixed by 3c3c237

**Comment by Caedis** [comment]
Gotcha, i'll pull and test with another large craft

**Comment by Caedis** [comment]
Looks good, no more NPE
