### ISSUE TITLE
[Feature] Renaming interfaces

### ISSUE THREAD

**Issue by Xikaro** [PrototypeTrousers/Applied-Energistics-2#153]
**Describe the feature**
Add the ability to rename interfaces, this would be useful when using them with gregtech multiblocks and other machines, it will help identify them in the interfaces terminal

**Reasons why it should be considered**
This can be implemented in the interfaces terminal itself, *screenshot*, as I highlighted

Or it can be implemented by gregtech, if so, then let me know, I'll write it there, for example, rename buffers, *screenshot*, or another option, so that ae pulls up the name that was made for the machine using the anvil

**Additional Context**

![image](https://user-images.githubusercontent.com/55663835/194806709-1ad4f3a9-bbf3-4b7d-9109-5dca9cf6fae3.png)
![image](https://user-images.githubusercontent.com/55663835/194806734-d0a5d277-1dc7-4368-9324-20536362411a.png)
![Screenshot_259](https://user-images.githubusercontent.com/55663835/194806817-59592da2-f181-4e88-ae04-eab875e00f7f.png)

**Comment by KorewaLidesu** [comment]
?
Aint there inscriber press option available?

**Comment by Xikaro** [comment]
hmm

**Comment by Xikaro** [comment]
for some reason I didn't check it

**Comment by Xikaro** [comment]
![Screenshot_260](https://user-images.githubusercontent.com/55663835/194809443-ecb8ca25-74cf-4b8a-af54-65e80c0662b4.png)
thanks it works

**Comment by nemo48rus** [comment]
In some reason - it dont rename GT buffers in terminal of interfaces

**Comment by ghzdude** [comment]
There's the AE Quartz Knife which can rename interfaces in-world, without needing an anvil

**Comment by YoungOnionMC** [comment]
I added the renaming feature with a cutting knife a while back

**Comment by calvissuperman** [comment]
Would be nice to have OP's method instead of using anvils. Not explicitly stated and somewhat of a hassle.
