### ISSUE TITLE
Integration problems with AE2WT

### ISSUE THREAD

**Issue by YiRanMushroom** [PrototypeTrousers/Applied-Energistics-2#158]
The amount of item in player's inventory couldn't display when using a wireless terminal(it looks like every item's amount is 1).
here are two pictures concerning the problem.
this is the normal one:
![normal](https://user-images.githubusercontent.com/114495322/196466721-48a9ed47-8ea0-4659-87da-505d46927af5.png)
this is the one with problem:
![invalid](https://user-images.githubusercontent.com/114495322/196466785-f92acb59-c22f-4cdd-a2c7-d70d090fadd3.png)

**Comment by Exaxxion** [comment]
I think Proto fixed this with 0e0729166f0e1bc0589b85e5b9055c31c46c28c3, try updating to [0.54.1](https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life/files/4033941)
