### ISSUE TITLE
Issue when items enter ME network

### ISSUE THREAD

**Issue by ghzdude** [PrototypeTrousers/Applied-Energistics-2#16]
Using PAE2 v39
**Describe the bug**
When an item enters the ME network, the amount of said item randomly changes rapidly until settling on the correct amount

**To Reproduce**
1. Try to craft an item, or insert an item manually
2. When the item enters the network, the amount changes wildly

**Expected behavior**

Amount should only update once to match the correct amount.

**Additional context**
https://user-images.githubusercontent.com/44148655/117560826-013e6e00-b046-11eb-8798-e229074c2551.mp4

**Comment by Caedis** [comment]
Also happens on server

https://user-images.githubusercontent.com/18713839/117563893-96edf380-b06e-11eb-8956-c8a4266b17c4.mp4

**Comment by PrototypeTrousers** [comment]
now really fixed in v39f
