### ISSUE TITLE
The mine code replacement function of the me augmented sample terminal is invalid

### ISSUE THREAD

**Issue by yang-fu** [PrototypeTrousers/Applied-Energistics-2#167]
<img width="517" alt="image" src="https://user-images.githubusercontent.com/66714394/197395997-da8766f4-179c-4995-84e6-206bcd2d647c.png">
The mine code replacement function of the me augmented sample terminal is invalid

appliedenergistics2-rv6-stable-7-extended_life-v0.54.3.jar

MC 1.12.2

**Comment by PrototypeTrousers** [comment]
These buttons arent my buttons, did you add Not Enough Energistics to your mods
also V0.54.3 is very old
