### ISSUE TITLE
Crashing on v39 when starting big craft

### ISSUE THREAD

**Issue by Caedis** [PrototypeTrousers/Applied-Energistics-2#17]
**Describe the bug**
Crash on starting large craft (10 infinity ingots)

**Expected behavior**
No crash

**Additional context**
[Crash log Gist](https://gist.github.com/Caedis/c503b1f4f3f4c4602153761f388d71e3)

- Minecraft Version: 1.12.2
- AE2 Version: PAE2 v39
- Forge Version: 14.23.5.2855

**Comment by PrototypeTrousers** [comment]
hopefully fixed in 39b
