### ISSUE TITLE
Issue with patterns

### ISSUE THREAD

**Issue by LolBomer** [PrototypeTrousers/Applied-Energistics-2#170]
After using a pattern terminal to make a pattern, i get a "set" pattern, no flavor text, no recipe attached, and shifting doesnt show its recipe like it has before  currently version 0.53.5 due to modpack

i have tried multiple recipies, but i have a pattern terrminal, then a smart cable inbetween the controller and interface, with molecular assembler attached to the interface.  there is enough power input as everything is glowing and there is excess power stored. 

- Minecraft Version: 1.12.2
- AE2 Version: 0.53.5
- Forge Version:

**Comment by LolBomer** [comment]
![unknown](https://user-images.githubusercontent.com/116738991/198056101-67ead53b-3831-4f28-9276-060f8327166c.png)

**Comment by PrototypeTrousers** [comment]
this was fixed in 0.53.6
