### ISSUE TITLE
Sometimes player cannot take out the items in the ME Drive

### ISSUE THREAD

**Issue by FnTlv** [PrototypeTrousers/Applied-Energistics-2#172]
![DBQBFP$DZ}IF~Z50QM%5G2S](https://user-images.githubusercontent.com/102719034/198792776-c508b62e-e4ca-4657-b46b-f8050c0fbfac.png)
For example, the player clicks the iron ingot in the above figure,the iron ingot cannot be taken out,He's still in the ME Drive,But it has a chance to trigger, not every time
- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7-extended_life-v0.54.8
- Forge Version:2860

**Comment by PrototypeTrousers** [comment]
Do have enough energy cells on your network

**Comment by FnTlv** [comment]
> Do have enough energy cells on your network

yes，
but I seem to have forgotten to make one point，it happens in multiplayer，
The environment is spongeforge-1.12.2-2838-7.4.8-RC4141.

**Comment by FnTlv** [comment]
> Do have enough energy cells on your network
such as this
https://youtu.be/mv3L5AaWzU4

**Comment by PrototypeTrousers** [comment]
i have no idea what spongeforge does but something is broken
