### ISSUE TITLE
4k Storage Cell is named as 16k Storage Cell in display name

### ISSUE THREAD

**Issue by SovereignEternal** [PrototypeTrousers/Applied-Energistics-2#179]
**Describe the bug**
The 4k storage cell has the wrong display name, it is currently named "16k Storage Cell". It has the proper tooltip description, "(x) of 4096 bytes used", it's only the name that's wrong.

**To Reproduce**
N/A

**Expected behavior**
Item should be named "4k Storage Cell".

**Additional context**
https://imgur.com/a/hdA0jwT

**Environment**
Noticed in modpack ProjectOzone3, version 3.4.6, using most recent version of AE2 UEL.

- Minecraft Version: 1.12.2
- AE2 Version: 0.53.8
- Forge Version: 14.23.5.2860

**Comment by ghzdude** [comment]
This issue has already been fixed in the latest versions of AE2 Unofficial Extended Life
in this commit https://github.com/PrototypeTrousers/Applied-Energistics-2/commit/4c8ad878752456f6b6087ced1df8874a9b744bf5
