### ISSUE TITLE
Missing texture on the terminals?

### ISSUE THREAD

**Issue by RefotsirkNged** [PrototypeTrousers/Applied-Energistics-2#183]
Texture seems to be missing on the terminals. They look normal on the item icon, its only in-world the problem appears.

![image](https://user-images.githubusercontent.com/6652640/201115496-b8f14985-06e4-44e9-8ee1-3f385833ef10.png)

This is on the modpack PO3, with a server and client both running on my local pc.

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7-extended_life-v0.53.8
- Forge Version: 14.23.5.2860

**Comment by RefotsirkNged** [comment]
Terminals are in the back of the pic. Left is pattern terminal, right is crafting. both still function normally, just visually weird :)

**Comment by PrototypeTrousers** [comment]
some performance mod you added to your instance does this, restart your client.

**Comment by RefotsirkNged** [comment]
Right! That would make sense. Thx 🙏
