### ISSUE TITLE
Inventory Tweaks sorting broken

### ISSUE THREAD

**Issue by Sandman366** [PrototypeTrousers/Applied-Energistics-2#187]
**Describe the bug**
In AE2EL v0.53.7b, sorting items by Inventory Tweaks works as it has for....I don't even know, probably however long AE2 has been on 1.12. In v0.53.8, the sorting is completely different, and this persists through to v0.54.11 (current latest as of writing). Oh, and sort order (ascending/descending) also doesn't seem to work while set to invtweaks sorting.

**To Reproduce**

Set terminal sorting method to InventoryTweaks.
![ae2 inventory tweaks sorting - not expected](https://user-images.githubusercontent.com/47545215/202074717-8a73774e-ac8a-4b2c-be76-5d3fcae34b22.png)

**Expected behavior**

I thought the order items would go in would look like this.
![ae2 inventory tweaks sorting - expected](https://user-images.githubusercontent.com/47545215/202074550-beca1d66-7734-4762-a226-b9cdfda1ba86.png)

**Additional context**
While trying to glance around for which version the issue started happening, the broken sort given wasn't always the same. (Yes, I in one test literally only changed what version of ae2 was installed, and the sorting order tweaked itself, but was still wrong.) In another test I tried having bogosort at the same time, which completely broke AE2's sorting (changing sort order and mode both did nothing).

I was running a barebones environment to try to find the version this started happening in, and made a tiny system that I dumped a bunch of random items into to test/show, and it didn't happen here, but in another pack I was playing (with a much more complete and well-filled ME system) I saw what looked like #154 's flashing items in first slot bug.

**Environment**
- Minecraft Version: 1.12.2
- AE2 Version: 0.54.11 (but I think anything after .53.7b has the issue)
- Forge Version: 12.23.5.2860
Only other mods I added to this environment were JEI (1.12.2-4.16.1.301) and Inv Tweaks (1.63 is only stable version listed for 1.12, but updating to 1.64+dev.151 doesn't help).

**Comment by PrototypeTrousers** [comment]
fixed in 0.54.13

**Comment by Sandman366** [comment]
Yay, thank you!
