### ISSUE TITLE
Crash when placing cables when NEE 2.0.0

### ISSUE THREAD

**Issue by mczph** [PrototypeTrousers/Applied-Energistics-2#191]
**Describe the bug**
Crash when placing cables

**To Reproduce**
Place any kind of ME cables

**Expected behavior**
No crash

**Additional context**
[crash-2022-11-27_13.26.03-client.txt](https://github.com/PrototypeTrousers/Applied-Energistics-2/files/10097594/crash-2022-11-27_13.26.03-client.txt)

**Environment**
In pure pae2 environment,it's fine.

- Minecraft Version: 
- AE2 Version: appliedenergistics2-rv6-stable-7-extended_life-v0.54.15
- NEE Version: NotEnoughEnergistics-1.12.2-2.0.0
- Forge Version: 14.23.5.2860

**Comment by vfyjxf** [comment]
This is a nee problem, I will fix it later.
