### ISSUE TITLE
How to actually double/halve the configured item amount in ME Interface?

### ISSUE THREAD

**Issue by mycroftjr** [PrototypeTrousers/Applied-Energistics-2#195]
Is there a way in 0.54.9 (or later) to actually double/halve the configured item amounts in the ME Interface? https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life/files/4032765 says
```
Interfaces can now hold up to 512 items in each slot

 SHIFT+MOUSE WHEEL UP/DOWN to DOUBLE/HALVE the configured amount
```
but that only increments/decrements the count for me.

**To Reproduce**
Click 64 of an item into an ME Interface autostock configuration slot, then let go of the items and shift + Mouse Wheel scroll up

**Expected behavior**
The configured amount of the item should double to 128 (or if +1/-1 is intended for Shift + Mouse Wheel scroll, an alternate set of controls to do so be documented)

**Environment**
On a localhost server world, modpack is Divine Journey 2 v2.18.0

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7-extended_life-v0.54.9
- Forge Version: 14.23.5,2860

**Comment by ghzdude** [comment]
ah, you're talking about the config slots of an interface, my bad.
in which case, the most you can do is shift + scroll wheel for now

**Comment by PrototypeTrousers** [comment]
Looks like the key combo is actually CTRL + Shift + Mouse wheel to double/halve.

**Comment by mycroftjr** [comment]
> Looks like the key combo is actually CTRL + Shift + Mouse wheel to double/halve.

when I try that, the config slot gets cleared and 127 of the item briefly appear in the output slot. Relogging does not change this.

**Comment by mycroftjr** [comment]
remaking for clarity
