### ISSUE TITLE
Interface identification via the interface terminal

### ISSUE THREAD

**Issue by BronsonMagnan** [PrototypeTrousers/Applied-Energistics-2#2]
**Describe the feature**

Add a button in the interface terminal adjacent to each interface. The button should toggle a blinking illumination effect on the corresponding interface in the world.

**Reasons why it should be considered**

This can make it easier to find an interface to fix an issue in a large OmniFactory AE network. For example not auto outputting, or the need to hide an interface. Think of it like tracking down a bad hard drive in a datacenter full of servers.

**Additional Context**

Maybe a possible integration with JourneyMap to drop a waypoint.

**Comment by PrototypeTrousers** [comment]
closed by https://github.com/PrototypeTrousers/Applied-Energistics-2/commit/bc2e4c84b975f8b84df18d7a89200af57153df53
