### ISSUE TITLE
[Mod Compat Bug]Crash with tick central

### ISSUE THREAD

**Issue by mczph** [PrototypeTrousers/Applied-Energistics-2#206]
**Additional context**
crash report
https://mclo.gs/MVQIVlF

**Environment**
ic2 is not loaded,I tried to turn ic2 compat OFF in config but not useful.
don't crash in pure pae2+tick central+lag goggles environment.

- Minecraft Version: 
- AE2 Version: appliedenergistics2-rv6-stable-7-extended_life-v0.54.19
- Forge Version:14.23.5.2860

**Comment by KasumiNova** [comment]
和 Tick Central 应该无关。

**Comment by mczph** [comment]
移除Tick Central后就没问题了，如何解释（）

**Comment by KasumiNova** [comment]
我没在错误报告里面找到任何与 TickCentral 有关的报告。

**Comment by mczph** [comment]
是这样的

**Comment by mczph** [comment]
tick central is too old and it's not compt with so many modern mods.It has crashed with other mods in my pack too.

**Comment by mczph** [comment]
Reply after a long time: It seems that this problem does not currently exist in my modpack, close.
