### ISSUE TITLE
Problems with wireless crafting terminal

### ISSUE THREAD

**Issue by YiRanMushroom** [PrototypeTrousers/Applied-Energistics-2#217]
- AE2 Version: extended_life-v0.55.1
Could not demand AE2 craftings through a crafting terminal without holding it on the main hand (it is in the inventory and opened by hotkeys).
If so then the UI of the crafting terminal would close but if holding it on the main hand the craft would be started successfully.

**Comment by KorewaLidesu** [comment]
Any log available?
Debug/latest

**Comment by YiRanMushroom** [comment]
[debug.log](https://github.com/PrototypeTrousers/Applied-Energistics-2/files/10686261/debug.log)
[latest.log](https://github.com/PrototypeTrousers/Applied-Energistics-2/files/10686262/latest.log)

**Comment by YiRanMushroom** [comment]
The problem hadn't still been totally fixed yet, the UI that allows user to confirm the order would still disapear (even though the Set Amount UI works effectively).

**Comment by YiRanMushroom** [comment]
In v0.55.3 crafts can be started without holding it, but the UI of it would disappear after starting a craft, which should be considered abnormal since it would not be closed after starting a craft when holding it.
