### ISSUE TITLE
Fluid Storage bus not filtering properly - Omnifactory Dev 2.9.4 nightly 20150209

### ISSUE THREAD

**Issue by Selway00** [PrototypeTrousers/Applied-Energistics-2#23]
**Describe the bug**

Fluid storage buses are not honoring proper formatting.  They will insert any available liquid into a tank even if it has the proper formatting.
Workaround: Format every single open spot on the fluid storage bus with the same fluid.  Then it cannot insert the wrong fluid.

**To Reproduce**
Place fluid storage bus.  Format it with liquid A.  Also have liquid B entering the AE system looking for a container.  The fluid storage bus will sometimes insert fluid B through a fluid storage bus formatted with fluid A.  

**Expected behavior**
The fluid storage bus does not insert any fluid other than the formatted one.

**Additional context**
None other than this mod is amazing and has improved performance so much my mind is blown.  Thank you.

**Environment**
- Omnifactory Dev 2.9.4 nightly 20150209

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7.omni-fixes-v40b
- Forge Version: 14.23.5.2855

**Comment by PrototypeTrousers** [comment]
fixed by 33946438bd3d4e4d5e19292e2242416e0d7113ac
