### ISSUE TITLE
"me interface" + "crafting card" = no "crafting behavior" tag/button

### ISSUE THREAD

**Issue by weoriu** [PrototypeTrousers/Applied-Energistics-2#233]
trying to make level maintainer for items with long crafting time. Use "me interface + crafting card + storage bus". After adding "crafting card" to "me interface" DONT appear tag/button "crafting behavior" on left part of interface GUI. Screenshot at end

**Describe the bug**

**To Reproduce**
  Place down "ME Interface"
  Open "ME Interface" GUI
  Insert "Crafting card"

**Expected behavior**
  appearing tag/button "crafting behavior" on left part of screen

**Additional context**

![image](https://user-images.githubusercontent.com/126128166/220804583-97486078-e4e4-4506-8aa0-94a7493c47d0.png)

**Environment**

tried other versions of PTAE2:
  appliedenergistics2-rv6-stable-7-extended_life-v0.53.3.jar
  appliedenergistics2-rv6-stable-7-extended_life-v0.53.8.jar
  appliedenergistics2-rv6-stable-7-extended_life-v0.54.19.jar
  appliedenergistics2-rv6-stable-7-extended_life-v0.55.5.jar

SP world
modlist:
  appliedenergistics2-rv6-stable-7-extended_life-v0.55.8.jar
  EnableCheats-1.12.2-1.0.0.jar
  HadEnoughItems_1.12.2-4.23.0.jar
  theoneprobe-1.12-1.4.28.jar

- Minecraft Version: 1.12.2
- AE2 Version:  appliedenergistics2-rv6-stable-7-extended_life-v0.55.8.jar
- Forge Version: 14.23.5.2860

**Comment by YiRanMushroom** [comment]
Originally the crafting behavior only exists in an export bus, which I don't think was achieved in ME interfaces in PAE2.

**Comment by weoriu** [comment]
Thanks about clearing my mind!
