### ISSUE TITLE
Incorrect behaviour happens when using a storage bus to the drawer controller.

### ISSUE THREAD

**Issue by YiRanMushroom** [PrototypeTrousers/Applied-Energistics-2#239]
when using a storage bus to the drawer controller, inport and export bus cannot function correctly. While a terminal can run correctly.
This is a very strange bug since it happens in a very specific condition. I am using AE2 to build a subnet which is used to transport items from Deep Mob Evolution simulation chamber, and I found AE2 import bus cannot import items from the simulation chamber to the drawer controller, which is connected by a storage bus.

WHILE:
1.if ME system connects to another container it can import successfully.
2.Other conduits can export things from the chamber.
3.Import bus can import things from other containers to the drawer controller.

So I don't know the reason, maybe its a bug of DME, I would also post this issue there.

**Comment by YiRanMushroom** [comment]
The export bus is okay but the import bus is not.

**Comment by serenibyss** [comment]
Crossposted with https://github.com/floppaxd/DeepMobEvolution/issues/21 (posting to link them in github)
