### ISSUE TITLE
AE2 P2P Energy Tunnel and DE Energy Pylon crash

### ISSUE THREAD

**Issue by TheRealPhyton** [PrototypeTrousers/Applied-Energistics-2#25]
I have the DE Energy Core T8 and I attached some P2P tunnels to the Pylons. I dont know what of them is the issue since I cannot even enter in the world rn (instant crash). A minute ago was perfectly fine, a minute later it crashed.

**To Reproduce**

I don't know if it is replicable in other world since i changed nothing and it crashed. In case: insert in the battery the energy from multiple sources with p2p tunnel, every tunnel has a different energy setup. For example 1 is solar power, 1 is numismatic, 1 is diesel. 
Another P2P Tunnel that extract from the battery and powers everything
The energy for powering the ME is on another energy pylon 

**Expected behavior**

In and Out from the battery with p2p tunnels

**Additional context**

https://pastebin.com/kHSWGWbz

- Minecraft Version: 

- Pack: Omnifactory 1.2.2
- AE2 Version: appliedenergistics2-rv6-stable-7.omni-fixes-v41c.jar
- Forge Version: 14.23.5.2847

**Comment by ghzdude** [comment]
If you want a quick solution to enter your world, you can set `B:removeErroringTileEntities=false` to true and enter you world. Once you enter you world, make the changes to your P2P, and leave to set `B:removeErroringTileEntities` back to false. I and another user have also experienced this issue.
