### ISSUE TITLE
[Crash] Client crash when highlighting an interface in a different dimension

### ISSUE THREAD

**Issue by asoftbird** [PrototypeTrousers/Applied-Energistics-2#27]
**Describe the bug**

When highlighting interfaces in the Interface terminal, highlighting interfaces located in different dimensions will crash the client.

**To Reproduce**

Have an interface in a different dimension linked through quantum gateways. 
Use an interface terminal in one dimension to highlight the interface in the other dimension.

**Additional context**

Crash log: https://paste.dimdev.org/akezuxepul.mccrash

(note that the crash log reports the error occuring in DIM0; the interface terminal was accessed from DIM-119)

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7.omni-fixes-v41d
- Forge Version: 14.23.5.2855

**Comment by BalaM314** [comment]
Created a pull request to fix it.
@PrototypeTrousers by the age of this issue it seems you missed it so I'm mentioning you.
I randomly ran into this issue and decided to fix it :) love knowing java
