### ISSUE TITLE
Wireless terminals may not save their internal inventory when in baubles slot

### ISSUE THREAD

**Issue by DeadlySprinklez** [PrototypeTrousers/Applied-Energistics-2#270]
**Describe the bug**

During a playthrough of Divine Journey 2, my friend and I manually updated to the newest version of AE2 UEL to rid ourselves of the constant server restarts that we kept needing to do thanks to a bug in AE2WTLib that caused our autocrafting to stop functioning with their terminals. (The terminals in the updated version of AE2 UEL are much better functioning, thankfully.)

However, during a call I realized that I could mount my crafting terminal in a bauble slot, open the GUI, take the magnet card out, close and reopen the GUI, and now I would have two magnet cards. I haven't tested this with the crafting grid, view cells, or other wireless terminals, though I do expect similar results if this is an issue with NBT saving.

**To Reproduce**

1. Take a linked and powered wireless crafting terminal and insert a magnet card.
2. Place the wireless crafting terminal into a baubles slot.
3. Open the terminal GUI through a keybind.
4. Either take the magnet card out and place it in your inventory, or attempt to toggle the state of the magnet card.
5. Close and reopen the terminal GUI.
6. Find the magnet card in the card slot has reappeared/retained its original state.

**Expected behavior**

The magnet card slot in the wireless terminal should have maintained its state when the terminal GUI was closed

**Additional context**

N/A

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7-extended_life-v0.55.12
- Forge Version: 14.23.5.2860
- Tested on a Divine Journey 2 v2.19.3 multiplayer server

**Comment by IntegerLimit** [comment]
I believe v0.55.13 released, although I am not sure. I would recommend seeing if there is a later release, and seeing if the issue still occurs on the latest release.

**Comment by BlazeHunterVN1610** [comment]
I have the same issue, but in v0.55.13

**Comment by xyrc1** [comment]
Had the same problem on Nomifactory CEU, though it was voiding items I put in the grid after I closed and reopened it.

**Comment by Bookh1ll** [comment]
I also had this problem, turns out a EnderIo wireless charging antenna was causing it. I managed to replicate it here on Nomifactory CEu 1.6.1-beta-3a:

https://github.com/PrototypeTrousers/Applied-Energistics-2/assets/128931567/69bfa686-d54f-4bfb-8184-71b00dc23178
