### ISSUE TITLE
Smart Dense cables act like smart normal cables. (They only take 8 channels and then stop working.)

### ISSUE THREAD

**Issue by gavinops** [PrototypeTrousers/Applied-Energistics-2#285]
**Describe the bug**

So I was just setting up a P2P Tunnel for my Drives and then I noticed the Dense Cables stopped Handing out Channels when they reached 8 Channels.

**To Reproduce**

Link up a P2P between the controller and some drives. Then link those drives to a Dense Cable on the Output P2P. And then you're done.

**Expected behavior**

The dense cable to output more than 8 Channels and power mah drives.

**Additional context**

![help](https://github.com/PrototypeTrousers/Applied-Energistics-2/assets/72882252/aa90613c-86d0-47b0-a1a4-8f3c200954d8)

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: Extended Life RV6-Stable 0.55.14
- Forge Version: 14.23.5.2860

**Comment by WaitingIdly** [comment]
a Dense Cable can carry up to 32, but a ME Drive can only carry up to 8 - if my reading is correct, you are connecting to the other Drives through a single Drive, and thus bottlenecking your channel capacity to 8.

**Comment by gavinops** [comment]
OH. So thats why. I call this closed. Reason: Me not knowing how drives work
