### ISSUE TITLE
 Severe FPS Drop When Performing Terminal Searches with P2P Connection

### ISSUE THREAD

**Issue by shane04111** [PrototypeTrousers/Applied-Energistics-2#286]
**Describe the bug**
When I use P2P connection to open the terminal and perform searches, my client experiences a severe drop in frame rate. This issue not only affects the smoothness of the gameplay but also impacts the overall user experience. The frame rate drops worsen as the number and variety of craftable items increase.

**To Reproduce**

1. Launch the game and enter the world.
2. Open the terminal interface.
3. Perform a search when there are a few stored item types and observe the frame rate.
4. Gradually increase the number of stored item types in the entire system.
5. Perform another search and observe if there is a noticeable frame rate drop.

**Expected behavior**
I expect the frame rate to remain stable when using the terminal search functionality with P2P connection, regardless of the number and variety of craftable items. The performance degradation should not significantly affect the frame rate, ensuring a smooth and enjoyable user experience.

**Additional context**
Before searching with multiple item types.
![many items before search](https://github.com/PrototypeTrousers/Applied-Energistics-2/assets/57738232/735d0ffd-b19e-434d-b66d-967dc1e84d17)

After searching with multiple item types.
![many items after search](https://github.com/PrototypeTrousers/Applied-Energistics-2/assets/57738232/0dc072da-d3d6-44d8-95d1-34bf9b1dbf4b)

Before searching with few item types.
![few items before search](https://github.com/PrototypeTrousers/Applied-Energistics-2/assets/57738232/749cb733-0b21-48ed-881b-29cd033078cf)

After searching with few item types.
![few items after search](https://github.com/PrototypeTrousers/Applied-Energistics-2/assets/57738232/375a855f-b3a2-45f3-a577-4f32a664bfa8)

video 
https://github.com/PrototypeTrousers/Applied-Energistics-2/assets/57738232/11587ba4-7e79-420e-a31f-4f679c132777

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7-extended_life-v0.55.15.jar
- Forge Version: 14.23.5.2860
- Installed Mods List: https://pastebin.com/6nZ5wUz1
- world: https://www.dropbox.com/s/u71fgvvvoczuxss/world.zip?dl=1

**Comment by 0xC4DE** [comment]
Does this happen when you decrease terminal size? What is your allocated memory, memory speed, and memory capacity (of your irl computer) It has to do with first-time loading/caching of items.

Think of opening JEI in a modpack with 30/40 pages of items. It will always lag the first time but will cache them, only if there's enough memory. If there's not enough memory, it will have to re-cache each time. I think that's happening here. AKA sounds like a client issue

**Comment by PrototypeTrousers** [comment]
should be fixed now, tried in po3 with the chamber thing with the tome of knowledge
