### ISSUE TITLE
Incorrect items in Crafting Terminal from JEI

### ISSUE THREAD

**Issue by ghzdude** [PrototypeTrousers/Applied-Energistics-2#29]
**Describe the bug**
Clicking the plus in JEI pulls the incorrect items

**To Reproduce**
Click the plus in JEI while in the crafting terminal to pull the items from AE.

**Expected behavior**
AE2 should only pull the items that match the items NBT/Metadata in JEI, otherwise it shouldn't pull.

**Additional context**
Trying to craft a chem bath while not having the items for it results in the below.
![image](https://user-images.githubusercontent.com/44148655/121986912-485a0600-cd4c-11eb-973c-b3ff92954f6a.png)

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: PAE2 V42b
- Omni Dev - commit 2d3d103

**Comment by asoftbird** [comment]
Can confirm. Note that this only happens to items which are not available in the system; items that are available are pulled correctly.

**Comment by ghzdude** [comment]
Most items are now correctly pulled into the crafting grid in the crafting terminal, but pulling a recipe that uses a tool from JEI puts the incorrect tool in the crafting grid, either from inventory or AE2 storage
![image](https://user-images.githubusercontent.com/44148655/122170607-9b5ab880-ce33-11eb-824d-0ccacd5963e3.png)
