### ISSUE TITLE
Interface terminal, button to jump to next free Molecular Assembler space

### ISSUE THREAD

**Issue by BronsonMagnan** [PrototypeTrousers/Applied-Energistics-2#3]
In the Interface terminal, add a button to jump to next interface named Molecular Assembler that contains an empty recipe slot

**Describe the feature**

Button when clicked should scroll the interface terminal down to the first interface named "Molecular Assembler" with a free space available.

**Reasons why it should be considered**

This could make it more convenient instead of wasting time on scrolling the interface terminal when adding many patterns

**Additional Context**

Jimmy wished for it on stream

**Comment by PrototypeTrousers** [comment]
fixed by #4
