### ISSUE TITLE
is there config with patten encode processesmod and crafting mode/how to turn it on

### ISSUE THREAD

**Issue by akasia** [PrototypeTrousers/Applied-Energistics-2#30]
about patten encode i see jimmycoa using just auto swhitch craftingmode and processes mod is that feature need to turn on on cofig ?
and 1 more thing that every time i loging to my single play world i hv to reconnect my me cable to let system to reconice that i on9 if not that 1 off my channel stay offline

**Comment by akasia** [comment]
by the way i using appliedenergistics2-rv6-stable-7.omni-fixes-v42d.jar ver on multiblock madness v.1.1.3

**Comment by PrototypeTrousers** [comment]
1) is on by default
2) are you using ME conduits from Ender IO?

**Comment by akasia** [comment]
yes

**Comment by PrototypeTrousers** [comment]
for the encoding issue remove the mod "just enough energistics".
the channel issue i'do have to test with channels on. ill look into it

**Comment by akasia** [comment]
oh ok that just enough energistics cosing that issue thx 
and the channel issue i try blockupdate olso can't work just need to breakit and place it and that olso in 1 chunk 
![2021-06-20_10 05 39](https://user-images.githubusercontent.com/14824981/122659909-1531cf80-d1af-11eb-8611-1d7195e8af21.png)

**Comment by PrototypeTrousers** [comment]
do you remember when it stopped working? does it work normally on v41e ?

**Comment by akasia** [comment]
er.. never try with v41e just try on v42b 
after i try i let you know

**Comment by akasia** [comment]
nah still same when logging still same can't read out that channel

**Comment by akasia** [comment]
it just sudden work mayb i update to v43d navermind than
