### ISSUE TITLE
Crafting slow on newest version (v43)

### ISSUE THREAD

**Issue by MaxistheSpy** [PrototypeTrousers/Applied-Energistics-2#33]
I just updated omnifactory and decided to try out the new version with larger interfaces so manually added the jar. I have lazy ae2 installed incase that matters. autocraft requests took ages. I could request a single wood or 5k wood with almost no effort but anything more complex took a very long time. to the point where crafting was basicaly unusable. they did load. I set something to craft and came back and it eventualy loaded but that was a single item after several minutes. the problem seems to get worse the more of each item you request and the more steps the item recipe has 

**To Reproduce**
update omnifactory to dev-2d3d103 install v43 of pae2. if needed install lazy ae2 aswell. try and craft something with multiple steps it took several seconds to load the craft for a single wooden widget and crafting 10-100 wooden widgets took longer then i cared to wait but atleast a minute. A single t4mm took longer then a few minutes. 

**Expected behavior**
Crafts take a neglegable time unless its a large request. I downgraded to the version included with omni 2d3d103 and that basicaly instantly loads

**Environment**
MacOS mbpro 2020 before m1 i9 processor 64 gb ram integrated and dedicated gfx SP every mod is the same as omni with the exception of lazy ae2, libnine (lazy ae2s library), dank null 1.7.91,

**Comment by PrototypeTrousers** [comment]
should be fixed in v43b
