### ISSUE TITLE
Crash when importing recipe from JEI

### ISSUE THREAD

**Issue by Jimmy469** [PrototypeTrousers/Applied-Energistics-2#34]
When importing certain recipes from JEI, a crash is observed. Specifically, when importing sag mill recipes with chance outputs.

Shift-click the "+" in JEI to import a sag mill grinding recipe for ores.

Recipe imports. There may or may not be incorrect NBT data on the item, dependent on how the original mod codes its JEI integration to display chance outputs.

**Additional context**
https://paste.dimdev.org/totomazotu.mccrash

**Environment**

- Minecraft Version: 1.12.2 "Multiblock Madness" modpack 1.1.4 Single Player
- AE2 Version: appliedenergistics2-rv6-stable-7.omni-fixes-v43e.jar 
- Forge Version: 14.23.5.2854

**Comment by akasia** [comment]
same with me it just only happen with in put sagmill recipe olso crash but if using pulverizer it ok
by the way i using Compactor AE2 Version: appliedenergistics2-rv6-stable-7.omni-fixes-v43d.jar
