### ISSUE TITLE
interface with interface expansion card can't input patten from interface terminal at 3rd row and 4th row 1st and 2nd is ok just 3rd and 3th can't insert

### ISSUE THREAD

**Issue by akasia** [PrototypeTrousers/Applied-Energistics-2#35]
interface with interface expansion card can't input patten from interface terminal at 3rd row and 4th row 1st and 2nd is ok just 3rd and 3th can't insert
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional context**

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: V43e/v43d
- Forge Version:14.12.5.2854

**Comment by PrototypeTrousers** [comment]
are you trying to insert more than one of the same pattern on one interface ?

**Comment by akasia** [comment]
nope just difren patten can take from 3/4 row just can't insert in

**Comment by akasia** [comment]
ok it fix just upadate to v43f thx
