### ISSUE TITLE
Compacting drawer bug

### ISSUE THREAD

**Issue by Leclowndu93150** [PrototypeTrousers/Applied-Energistics-2#38]
**Describe the bug**
with drawers be aware that there's a bug where the me system gets confused by compacting drawers, since the drawer presents both ingots and blocks it means recipes think both are available

**To Reproduce**

**Expected behavior**

**Additional context**

**Environment**

- Minecraft Version: Omnifactory Modpack
- AE2 Version: Omnifactory Modpack
- Forge Version: Omnifactory Modpack

**Comment by PrototypeTrousers** [comment]
yes. a message shows up in chat to tell you that now.
