### ISSUE TITLE
A pattern is still displayed on the network after it has been removed.

### ISSUE THREAD

**Issue by jk1895** [PrototypeTrousers/Applied-Energistics-2#42]
Hi,
no idea if this is a bug or if this is part of the performance improvements.
When I remove a described pattern from an interface, the recipe is still shown as craftable. Only after I reload the world the recipe disappears in the terminal. This is quite confusing.
I observed this in version v43h and then updated to version v45b where it is the same. (Forge 14.23.5.2855, Omnifactory modpack dev version 2d3d103)

Otherwise, thanks for this awesome version of AE2!

**Comment by ebmusicman84** [comment]
This also appears to continue to occur in v45f.  Created a system with a crafting terminal, pattern terminal, creative energy cell, and interface.  Created a pattern for Reinforced Conversion Kit and inserted it in to the interface.  Pattern properly showed and listed steps to craft.  Removed pattern from the interface, pattern continued to show and did not list any crafting steps.

![image](https://user-images.githubusercontent.com/14189589/127178448-ff5fcf68-9118-4486-bd47-0fa945c8121c.png)

**Comment by jk1895** [comment]
I haven't tested v45f yet, but in v45e this bug was definitely fixed for me.

**Comment by ebmusicman84** [comment]
Can confirm it happened for me in 45f, it appears to be resolved as of 45g though.
