### ISSUE TITLE
Crash on World Load

### ISSUE THREAD

**Issue by ghzdude** [PrototypeTrousers/Applied-Energistics-2#44]
Tried loading into my world with PAE2 v45g, but was met with an immediate crash.
[crash-2021-07-27_14.15.24-server.txt](https://github.com/PrototypeTrousers/Applied-Energistics-2/files/6888794/crash-2021-07-27_14.15.24-server.txt)
Last known version where issue do not exist is v45e

- Minecraft Version: 1.12.2
- AE2 Version: PAE2 v45g
- Omni Dev (94c01dd)

**Comment by ebmusicman84** [comment]
Same issue, looks to be a Fluid Storage Bus problem. 

Here's a world load crash: http://paste.ubuntu.com/p/DzRHMzChV2/
And a crash when placing a fluid storage bus: http://paste.ubuntu.com/p/9tnGWdnrQH/

**Comment by PrototypeTrousers** [comment]
v45h should fix this. sorry.
