### ISSUE TITLE
Had two crashes related to storage buses.

### ISSUE THREAD

**Issue by jk1895** [PrototypeTrousers/Applied-Energistics-2#45]
Hello,
today Minecraft crashed twice when I was working with the memory buses.
The first crash I had the GUI open and wanted to assign an item to the bus with a shift-click.
Crash report:
[crash-2021-08-01_11.28.53-server.txt](https://github.com/PrototypeTrousers/Applied-Energistics-2/files/6913297/crash-2021-08-01_11.28.53-server.txt)

On the second crash I attached a memory bus to a lightly filled storage drawer.
Crash report (It generated two this time):
[crash-2021-08-01_21.40.24-client.txt](https://github.com/PrototypeTrousers/Applied-Energistics-2/files/6913300/crash-2021-08-01_21.40.24-client.txt)
[crash-2021-08-01_21.40.18-server.txt](https://github.com/PrototypeTrousers/Applied-Energistics-2/files/6913301/crash-2021-08-01_21.40.18-server.txt)

I am using this version:
appliedenergistics2-rv6-stable-7.omni-fixes-v45l.jar
By the way, I could not reproduce the first crash. On the second try it worked. That is why I did not report it.
The second crash came again now. Here is the new report:
[crash-2021-08-01_21.56.09-server.txt](https://github.com/PrototypeTrousers/Applied-Energistics-2/files/6913327/crash-2021-08-01_21.56.09-server.txt)

**Comment by PrototypeTrousers** [comment]
v45m should fix those crashes

**Comment by jk1895** [comment]
Wow, you're fast. :)
I will test it right away.
