### ISSUE TITLE
Crafting manager fallback config being ignored

### ISSUE THREAD

**Issue by RaVenInTheDark** [PrototypeTrousers/Applied-Energistics-2#46]
**Describe the bug**
Even when disabled in the config, ae2 falls back to the crafting manager when autocrafting. I do believe this is an issue with this fork, as the config has been respected properly in standard ae2 1.12.2.

**To Reproduce**
Disable crafting manager fallback in config, configure a pattern in a way where the crafting manager would be used and attempt to autocraft. This is best shown with a debugger or spark. 

**Expected behavior**
Ae2 does not fall back to the crafting manager and instead autocrafting fails to start. 

**Additional context**
![20210804_004242.jpg](https://user-images.githubusercontent.com/66441550/128101029-733df74c-022a-4774-a74a-e92c6f56513a.jpg) This is the only screenshot I have to hand, it's part of a spark profile. 
**Environment**

Running on the Omnifactory dev branch. I did not encounter this issue elsewhere.

**Comment by PrototypeTrousers** [comment]
make sure all you ME system is chunkloaded. this call to the crafting manager would not be affected by the fallback config option

**Comment by RaVenInTheDark** [comment]
The full network is loaded, yes. Why would this not be affected by the config, and what exactly *is* affected?

**Comment by PrototypeTrousers** [comment]
do you have the original spark profile?

**Comment by PrototypeTrousers** [comment]
please test with 45n

**Comment by RaVenInTheDark** [comment]
45n? I don't have the original profile to hand but I should be able to get a new one soon.

**Comment by PrototypeTrousers** [comment]
https://github.com/PrototypeTrousers/Applied-Energistics-2/releases/tag/omni-fixes-v45
v45n, latest jar

**Comment by RaVenInTheDark** [comment]
Can I safely update this on a server without requiring clients to update?

**Comment by PrototypeTrousers** [comment]
not really, it wont connect with mismatched versions sorry

**Comment by RaVenInTheDark** [comment]
I can deal with the version mismatch, that's an easy change. I was more on about whether there'd be actual issues with the changes that were made?
