### ISSUE TITLE
Some liquids are not colored on the Storage Monitor

### ISSUE THREAD

**Issue by hyodocraft** [PrototypeTrousers/Applied-Energistics-2#52]
**Describe the bug**
When liquids are displayed in the Storage Monitor, colors are not applied to some of the GTCE liquids and Xenon Gas etc.
https://i.imgur.com/aq1hepE.png

**To Reproduce**
Place the storage monitor on a powered network and use a bucket to display the liquid.

**Expected behavior**
All liquid colors are displayed correctly.

**Additional context**
GTCE ingots, gears, etc. don't have colors applied in the encoded pattern, but they are displayed with normal colors in the Storage Monitor.
https://i.imgur.com/oyaO54L.png
https://i.imgur.com/PDGTO40.png

Colored:  Oxygen, Hydrogen, Nitrogen, Chlorine, Methane, Radon, Canola Oil, Sulfuric Acid, Argon
No color: Epoxy Resin, Butene, Benzene, Rocket Fuel, Methanol, Phenol, Propane, Propene, Xenon Gas, Neon Gas

**Environment**
- Base Omnifactory Version: dev b6339c7
- AE2 Version: v46j

**Comment by PrototypeTrousers** [comment]
should be fixed by v46l (lower case L)
