### ISSUE TITLE
Power problem

### ISSUE THREAD

**Issue by jk1895** [PrototypeTrousers/Applied-Energistics-2#59]
Hello,
Today I had ~~3x~~ 4x no power. Just like that the whole ME system went out and no matter how many acceptors and conduits I had connected, it didn't come back on. I unplugged every other machine and had power in abundance, the ME systen would not turn on.
Only when I reload the world (not the whole game) the ME system has power again.
Maybe I'm just imagining it or maybe I'm doing something wrong, but I'm not doing anything I haven't done countless times in the past. I think there is a bug.

**Environment**
- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7.omni-fixes-v46o.jar
- Forge Version: 14.23.5.2855

EDIT:
It happened a fifth time. But it is actually that I run out of power (so my fault). But if I then unplug or disable all machines, then no matter how much power is available, I can't get the ME system to start. Only a restart of the world helps.

**Comment by jk1895** [comment]
Just happened again.
To show that I am not crazy, I cheated a creative energy cell and stuck it to an energy acceptor.
As you can see on the first picture, the ME system does not turn on.
![2021-09-04_22 22 58](https://user-images.githubusercontent.com/20401451/132107297-d562c8a9-7a48-482a-956b-3d213d1152b7.png)

On the second picture I reloaded the world. Everything lights up again.
![2021-09-04_22 23 23](https://user-images.githubusercontent.com/20401451/132107299-4bb7e178-ed39-4b9d-865e-e4b73f0c7406.png)

**Comment by jk1895** [comment]
One last time I'll bug you (I hope), because maybe I'm doing something wrong and just don't see it.
I'm playing with the newest version right now:
appliedenergistics2-rv6-stable-7.omni-fixes-v46p.jar
Again, I ran out of power.
Now I tried something else. I didn't disconnect all machine, but all AE2 cable, so only drives and consoles with dense power cells and power acceptor left.
The power came back, the power cells were charged.
Now I have restored all the connections.
And now I observe the following:
The energy acceptor does not receive enough energy (Not even if a creative energy cell is stuck to the acceptor!). For a short while both values are the same (pic1), then the energy input decreases(pic2), then increases again, then decreases.... until all dense energy cells are empty(pic3).

(Sorry I didn't switch the language, it just always takes forever to switch it.)
![2021-09-05_10 17 02](https://user-images.githubusercontent.com/20401451/132121190-62a6ca7e-da5e-4a5b-b25a-374ccf9bc810.png)

![2021-09-05_10 16 39](https://user-images.githubusercontent.com/20401451/132121185-fa21e73c-1f57-4458-bbc1-ef2abb93eb70.png)

![2021-09-05_10 17 25](https://user-images.githubusercontent.com/20401451/132121192-ff9be9f4-c337-449a-a538-6f097f00aaa6.png)

**Comment by PrototypeTrousers** [comment]
please try this one in v46q

**Comment by jk1895** [comment]
Dear PrototypeTrousers,
I would so much like to say now it works, but unfortunately it still happens. I'm worried that you'll eventually stop frustrated with this project. I hope not and we can continue to enjoy your brilliant work.
I spent two hours trying to figure out what could be causing this. First, I tried to force this bug by using an energy trash can. But unfortunately it can't be provoked that way.
When at some point the energy was gone again, I started to cut off parts of my base.
At first I thought it was my five 64k CPUs, but no, that wasn't it.
Then I was sure it must be AE2Stuff with the advanced engraving machines, also wrong.
Then I had it, I thought, the security console from AE2. But it wasn't that one either.
In the end I suspected PackagedAuto, but that wasn't it either.
It happens randomly, whether I actually run out of power or not. Then you can get the power back, either, I reload the world or I try to break random ME cables. Sometimes it works that way and energy flows again for a time.
Then it starts to get less again....
If you want I can try to make a video. Just don't know how.

**Comment by jk1895** [comment]
Sorry for not writing right away.
So with v46r it is that the stored energy value goes up and down constantly. This is new. But it goes at some point the energy back to 0. Takes a little longer now, but am not sure.
At the moment I always play with the creative energy source, otherwise it's no fun.
![2021-09-09_21 40 07](https://user-images.githubusercontent.com/20401451/132751974-3fe5344e-8d1c-4bea-8757-9390a09b53a8.png)

**Comment by jk1895** [comment]
If v46**t** was dedicated to the power issue, then it still does not work.

_Can't anyone confirm this bug and help here?_

One more thing I could mention, the dense energy cells never get all full and get emptier over time. Maybe this will help you...

**Comment by PrototypeTrousers** [comment]
try v46u... again...
if it does not work im gonna need your world

**Comment by jk1895** [comment]
Good morning.
Now it's even worse, a world reload won't bring the power back.
Since there seems to be no private messages here, please send me an email for the download link of my world. amortalist(at)gmail.com

**Comment by jk1895** [comment]
I closed my game, update from v46v to v46z, started the game and played a couple of hours. Maybe 3... it looked so good. Stored power showed max power minus energy usage all the time! Energy generation and energy usage were in sync all the time. All was good.
I closed the game to play another one.
After an hour, I loaded MC again. Started my world.... after a couple of minutes it happened again. Stored power decreased slowly. The dense energy cells drained one by one. After a while, energy generation shows 0.

I'm sorry, I suppose you have to go back further.

**Comment by ghzdude** [comment]
I've noticed that the Network Tool from AE2 is unreliable when it comes to reading the energy stored in the network. The stored power value fluctuating that jk1895 describes does occur, but the system or cells does not actually lose power. Though I haven't been playing Omnifactory recently, I've not observed my system turning offline due to power loss in versions 46i, 46o, 46r, 46t, and 46v. I also check v46z in a little bit.

**Comment by PrototypeTrousers** [comment]
the issue does occur on the save provided, but the timing is completely random. i've seen power issues on load and also worked fine for 16 minutes. after some changes im currently waiting to see if it happens again

**Comment by ghzdude** [comment]
are you sure it's not an issue with power generation? last time i had issues with my AE network flickering, it was because my machines were sucking up all the power.

**Comment by jk1895** [comment]
@ghzdude I have a Draconic Evolution energy cell attached to the energy acceptor. This thing is producing 2.1 billion RF/t. It should be enough.

@PrototypeTrousers Maybe, if you don't want to upload that many versions, you could send me your tries to my email. I would test it and report.

Greetings

**Comment by jk1895** [comment]
_I wish I could better English._

Strange thing is just happened.
I will try it to explain via screenshots:
I'm doing double packages to parallelize Draconic Evolution fusion crafting. Wyvern Core is my first item.
I have encoded and crafted the double package (I suppose you know what double packaging is).
And it is laying in the system:
![2021-09-18_20 52 13](https://user-images.githubusercontent.com/20401451/133905784-681b8d36-becd-45c1-b453-cec11d874b22.png)

The double package is encoded in a normal pattern, so I can order the Wyvern Cores:
![2021-09-18_20 52 24](https://user-images.githubusercontent.com/20401451/133905821-bf0d0bf2-361c-47c6-bf3a-7775bef9f159.png)
![2021-09-18_20 52 30](https://user-images.githubusercontent.com/20401451/133905822-b09ed02d-4114-49df-a3cc-5521b60b8771.png)

Now I removed the fluix cable:
![2021-09-18_20 52 59](https://user-images.githubusercontent.com/20401451/133905832-8e6ebe36-06d7-4040-a739-d19e695f191d.png)

The ME-system is showing 2 packages now!:
![2021-09-18_20 53 05](https://user-images.githubusercontent.com/20401451/133905845-80e8f2c6-c599-40b6-8ffd-27a0a3dc6714.png)

I can remove one:
![2021-09-18_20 53 16](https://user-images.githubusercontent.com/20401451/133905868-be54f500-aa9e-48b6-a535-28450cb6b320.png)

But I can't remove the second one:
![2021-09-18_20 53 22](https://user-images.githubusercontent.com/20401451/133905891-06550984-8099-453a-ab9a-ef3d79c959e1.png)

When I place the fluix cable back, the ghost item disappears:
![2021-09-18_20 53 35](https://user-images.githubusercontent.com/20401451/133905906-237023c5-d428-4c39-9e39-3f35ace68049.png)

![2021-09-18_20 53 43](https://user-images.githubusercontent.com/20401451/133905921-6dc3b653-f623-47c7-9137-a66d1bdd4054.png)

When I remove the one package and remove the cable afterwards, no ghost item is showing up.

The "bad" thing is, after I restarted the world (not the whole game) this bug is gone.

Greetings

**Comment by jk1895** [comment]
Hello Prototype,
just had another blackout (v47) and after I placed the energy cells differently and they filled up again afterwards, they are now getting emptier again very slowly.

I don't want to be the one who always brings you this bad news. Maybe there is just something broken in my world and it works for everyone else?
**Please tell me** if I should ignore this now? As I said, I don't want to be the one with the bad news and make your life difficult with it!
![2021-09-20_12 08 53](https://user-images.githubusercontent.com/20401451/133986063-7f6f4f3b-2419-4fb7-b03b-327fdc577e2c.png)
![2021-09-20_12 08 41](https://user-images.githubusercontent.com/20401451/133986067-0d98d349-3ed0-420b-b901-a9c14795e780.png)
