### ISSUE TITLE
Input Search of Patterns with Substitution matches on the not encoded substitution

### ISSUE THREAD

**Issue by Theisyat** [PrototypeTrousers/Applied-Energistics-2#6]
If you search for "A" as the input of a pattern where B can be substituted for A, all patterns with B also show up. 

**Expected behavior**
This should not happen

**Additional context**
Probably Error in src/main/java/appeng/client/gui/impl./GuiInterfaceTerminal.java:480
As the Displayname from the virtualItem probably is every substitution combined.

**Comment by PrototypeTrousers** [comment]
can you be more specific which pattern this happens ?
a magenta dye pattern encoded with substitutions on and using red pigment and white dye
did not show up on the search for 'rose' (from rose red)  or 'meal' (from bone meal as white dye)

**Comment by Theisyat** [comment]
I I thought I saw this bug on Jimmys Stream, but I made an error. Couldn't Reproduce the Behavior. Very Sorry.
