### ISSUE TITLE
Fluid emitter does not seem to count properly or works extremely slow.

### ISSUE THREAD

**Issue by jk1895** [PrototypeTrousers/Applied-Energistics-2#60]
Hello,
when I set 50 mB, the emitter does not respond until ~16 mB.
If I set 150 mB, it reacts at ~64 mB.
If I set 250 mB -> ~112 mB.
...

It's a small sub network, I've done this a few times and never observed this behavior. But maybethat's the way it should be?
![2021-09-05_13 09 51](https://user-images.githubusercontent.com/20401451/132124670-8ae49d61-47f4-4e03-bcc4-1bf23e7cc095.png)

**Environment**
- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7.omni-fixes-v46p.jar
- Forge Version: 14.23.5.2855

**Comment by PrototypeTrousers** [comment]
unless the tank emits block updates, like comparator signals, that forces the bus cache to reset, the bus can take between 5 and 60 ticks to update the count

**Comment by jk1895** [comment]
The emitter only reacts after about 20+ seconds. This does not feel right.
I loaded an old instance of Omnifactory for comparison. 1.2.1 was that with AE2 from Talchas (appliedenergistics2-rv6-talchas-7b.jar).
There it is that the emitter responds immediately. I have built exactly the same setup and set 100 mB. As soon as 96 mB were displayed, the emitter switched off to add new 144 mB.
Now that I can make video :)
My current world emitter set to 250 mB neodymium.
Here you go: https://youtu.be/puMajEnm8qA

**Comment by jk1895** [comment]
Good news! You are free. So with v46r it's still the same. The emitter reacts much too slow or late.
About 20 seconds is unacceptable.
I have now found that the emitter works correctly with any other fluid container (tanks from EIO, ThermalEx and even the barrels from SoG). So immediately switches, just not with the damn fluid input hatches. (I have tried different tiers).
I spent a long time today installing the many older versions to find the culprit. But it was always the same. Then I thought it must be GregTechCE itself! And probably it is, because I installed the old version of Talchas that worked on the old Omnifactory instance 1.2.1, and it didn't work either! So the old GregTechCE version is better than the latest. They must have changed something on those hatches, so that the emitter now reacts so sluggishly.
I hope you understand what I want to say.

Please excuse me if I caused you any worries.

Many thanks

**Comment by jk1895** [comment]
Sorry for not writing right away.
So with v46r it is that the stored energy value goes up and down constantly. This is new. But it goes at some point the energy back to 0. Takes a little longer now, but am not sure.
At the moment I always play with the creative energy source, otherwise it's no fun.
![2021-09-09_21 40 07](https://user-images.githubusercontent.com/20401451/132751974-3fe5344e-8d1c-4bea-8757-9390a09b53a8.png)
