### ISSUE TITLE
Crafting Job uses too many bytes

### ISSUE THREAD

**Issue by PanSzelescik** [PrototypeTrousers/Applied-Energistics-2#66]
**Describe the bug**
Crafting Job uses too many bytes

**To Reproduce**
Create Pattern 1 Awakened Draconium Block -> 9 Ingots
Insert into ME Interface next to Molecular Assembler
Try autocraft

**Expected behavior**
644,651 bytes it's definitely too much

**Additional context**
![Zrzut ekranu 2021-11-28 164417](https://user-images.githubusercontent.com/26679785/143775299-3ce65b48-45f4-45b6-8b83-9044d8505bfd.png)

I think the problem may be after this commit: https://github.com/PrototypeTrousers/Applied-Energistics-2/commit/b423d99879379e97d95e8a44c92f83a5f9980dce

**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7.omni-fixes-v47h.jar
- Forge Version: 2847

**Comment by PrototypeTrousers** [comment]
try with v47i
