### ISSUE TITLE
ME P2P tunnel doesn't connect on server, will not use given frequency

### ISSUE THREAD

**Issue by Knoedelwasser** [PrototypeTrousers/Applied-Energistics-2#69]
**Describe the bug**
I'm not able to connect 2 ME P2P tunnels with each other. The receiving tunnel doesn't use the given frequency but stays on 0000.
This problem only occurs on a server, NOT in singleplayer

**To Reproduce**
Play on a server -> simple ae2 setup -> SHIFT+RMB on sending me-p2p-tunnel -> RMB on receiving Tunnel -> receiving tunnel wont use frequency

**Expected behavior**
Receiving p2p tunnel says its linked to frequency "xxxx"

**Additional context**
![2021-12-20_12 17 26](https://user-images.githubusercontent.com/96481567/146944565-a62c2ce5-6117-4b0d-b717-27cc445fb74d.png)

**Environment**
Pack: Multiblock Madness 2.0.3
Multiplayer!

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7.omni-fixes-Experimental-v49
- Forge Version: 14.23.5.2855

**Comment by PrototypeTrousers** [comment]
fixed in v49l , but use v49n
