### ISSUE TITLE
Drag from JEI into Pattern Terminal

### ISSUE THREAD

**Issue by Caedis** [PrototypeTrousers/Applied-Energistics-2#7]
**Describe the feature**
Ability to drag items from JEI into the Pattern Terminal like how EnderIO filters work

**Reasons why it should be considered**
Having to manually create an item before being able to add it to a pattern can be annoying, especially for deep microcrafting in processing mode (like creating a rotors pattern, or like how Jimmy gets around the circuit replacements (keeping 1 of each circuit in a nearby chest))

**Comment by PrototypeTrousers** [comment]
I thought about this for i while and i can only suggest the following if you want the exact items in JEI in you patterns, use a dummy pattern terminal with no storage. that way it will only grab the items in JEI. the backside is the items may have different NBT than the ones in your system.

**Comment by Caedis** [comment]
Gotcha, thanks for the update.
