### ISSUE TITLE
Publication on CurseForge

### ISSUE THREAD

**Issue by SpeeeDCraft** [PrototypeTrousers/Applied-Energistics-2#71]
**Describe the feature**
Hello. I wanted to ask a question. Would you like to post this version of the mod on CurseForge so that any other modpack maker can use this version of AE2. If it can be used in modpacks that will be posted on CurseForge, could you explain how?

**Comment by PrototypeTrousers** [comment]
this mod is on the approved Non-Curseforge mods list already. twice even
https://docs.google.com/spreadsheets/d/176Wv-PZUo9hFxy6oC6N8tWdquBLPRtSuLbNK-r0_byM/edit#gid=23949688

curseforge sucks a bit with it though

**Comment by SpeeeDCraft** [comment]
Thanks for answer
