### ISSUE TITLE
Copying a processing pattern from JEI on top of a crafting pattern not working properly

### ISSUE THREAD

**Issue by Filostorm** [PrototypeTrousers/Applied-Energistics-2#72]
When copying a processing pattern from JEI on top of a crafting pattern, instead of properly switching and importing the recipe, it causes a soft crash (vanilla fix error pops up), and doesn't properly replace the items for the craft

**To Reproduce**
Import a crafting recipe, then import a processing recipe. (From JEI)

**Expected behavior**
It should replace the crafting grid recipe with the processing one.

[Crash Log](https://paste-bin.xyz/31284)

**Environment**
- Modpack: Multiblock Madness - Overloaded

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-trousers_edition-rv6-stable-7-v49r (Same issue in at least v49q)
- Forge Version: 14.23.5.2860

**Comment by PrototypeTrousers** [comment]
should be fixed in v49t
