### ISSUE TITLE
Autocrafting not recognizing valid substitutions

### ISSUE THREAD

**Issue by hjae78** [PrototypeTrousers/Applied-Energistics-2#78]
**Describe the bug**
I'm playing TJ2 and have started autocrafting. I have placed a recipe with substitutions enabled for an HV Mixer into my system. I also have recipes to autocraft circuits up to Refined Computer. Requesting an HV Mixer fails because there is no recipe for the Micro Assembly which the recipe is encoded with.

**Expected behavior**
That the system recognizes that any HV circuit is valid in the recipe.

**Additional context**

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7-extended_life-v49ac
- Forge Version: 14.23.5.2860

**Comment by PrototypeTrousers** [comment]
implemented in v51
