### ISSUE TITLE
GTEU to RF converters do not deliver correct amount of EU/t if the EU to RF conversion ratio is changed from 1:4

### ISSUE THREAD

**Issue by bruberu** [PrototypeTrousers/Applied-Energistics-2#8]
**Describe the bug**
In mods such as CEU and Gregicality that provide tools to convert between GTEU and RF, there exist config options to tweak the precise ratios between the two energy systems. However, when one attempts to change these options from the default 1:4 ratio, and then uses one of these converters on an energy acceptor, it appears that AE2 does not account for this shift. For example, if the ratio was changed to 1:2, then an EV CEU would only provide the equivalent of 1024 EU/t, while if it was changed to 1:8, it would provide 4096 EU/t. This behavior is the same across both CEU and Gregicality, and I could not replicate this for other mods, such as Refined Storage.

**To Reproduce**
1. Create an instance with Gregicality or CEU and all of their dependencies, along with this version of AE2 (although the latest version on the main branch of AE2 has this bug as well).
2. In the config for whichever mod you picked, set the ratio of EU to RF to 2 (or 1:2, for CEU).
3. Place an EU generator, an EU to RF converter, and then an Energy Acceptor, all next to each other.
4. Place a dense energy cell into the network, and add enough devices so that the network would need to use more than half of the expected energy that you are providing the system. (For example, an EV generator and converter should provide 2048 EU/t, so aim for 1025 EU/t and up.)
5. Get a network tool, and once all available energy buffers are depleted, you should see that the Energy Generation is exactly half of the expected value.

**Expected behavior**

Instead of showing half of that expected EU/t, it should instead show all of that generated power instead (such as 2048 EU/t in the case of using EV power).
**Additional context**

Here is what I got using CEU at 1:2, with an EV converter:
![2021-03-19_14 17 04](https://user-images.githubusercontent.com/80226372/111831772-d2194500-88bd-11eb-9ff5-701ee6689e84.png)

**Environment**
I'm working from the dev build of 0.21.3 Gregicality, although this bug exists for later versions of it as well.

Minecraft Coder Pack 9.42
CTM MC1.12.2-1.0.2.31
AE2 Trousers Edition rv6-stable-7 omni-fixes-v30b
CraftTweaker2 1.12-4.1.20.554
JEI 4.16.1.302
Forestry 5.8.2.387
CodeChicken Lib 3.2.3.358
Forge Multipart CBE 2.6.2.83
GTCE 1.10.8.599
CEU 1.0.5.1
Cucumber Library 1.1.3
Mystical Agriculture 1.7.3
Mantle 1.3.3.42
Tinkers' Construct 1.12.2-2.12.0.115
Mystical Agradditions 1.3.2
Refined Storage 1.6.15
CT-GUI 1.0.0
Forge Microblocks 2.6.2.83
Minecraft Multipart Plugin 2.6.2.83
The One Probe 1.12-1.4.23-16
Gregicality 1.12.2-0.21.3

- Minecraft Version: 1.12.2
- AE2 Version: omni-fixes-v30b
- Forge Version: 14.23.5.2847

**Comment by PrototypeTrousers** [comment]
Thats just a visual bug, as that EU/t means IC2 EU and not GTEU.
However if that bother you, you can change the ratio in the AE2 config file: 
```
powerratios {
    D:ForgeEnergy=0.5
    D:IC2=2.0
    D:UsageMultiplier=1.0
}
```
Try changing IC2 to 1.0

**Comment by bruberu** [comment]
Well, that fixes it. Thank you!
