### ISSUE TITLE
[Feature Request] Add automatic switching between crafting table mode and processing mod in pattern terminal

### ISSUE THREAD

**Issue by joendter** [PrototypeTrousers/Applied-Energistics-2#86]
If you try Move items on an other recipe type than currently selected it won't let you and you have to manually change the mode.
![image](https://user-images.githubusercontent.com/71767955/157412806-6958c91a-034b-4779-bea7-b775769c247c.png)

**Describe the feature**
The mode would be changed automatically on clicking the +

**Reasons why it should be considered**
This would be quite convenient and a nice qol feature.

**Comment by PrototypeTrousers** [comment]
uninstall just enough energistics :)

**Comment by joendter** [comment]
Thanks, it works now...
