### ISSUE TITLE
Level emitters are acting wonky

### ISSUE THREAD

**Issue by lesdmark** [PrototypeTrousers/Applied-Energistics-2#9]
**Describe the bug**

This is using 30c. For example I placed a level emitter told it to monitor blaze rods then set the number to 2000. Chose for the emitter to come on if level drops below this number. There are 4000 blaze rods in the system so the emitter stays off so far so good. Then you break the fluix cable running to the emitter because you are trying to tidy up, when the cable is reconnected the emitter comes on like you don't have the 2000. It is then stuck on and ignores the actual system inventory level. rebreaking the cable and replacing it does nothing

**To Reproduce**

place emitter, set object to be monitored, set level desired, set mode. break cable leading to emitter and reconnect emitter ignores actual inventory level from this point on. 

**Expected behavior**

Expect emitter not to ignore inventory

**Additional context**

**Environment**

This is Omnifactory being run on a MP server using dev snapshot 5573535

- Minecraft Version: 1.12.2
- AE2 Version: 30c
- Forge Version: 2847

**Comment by PrototypeTrousers** [comment]
362b001cb4d0a153daeef6687d19a421003976d5 should fix this.

**Comment by lesdmark** [comment]
That seems to have done the trick. Thanks!
