### ISSUE TITLE
Blocking Mode Crash

### ISSUE THREAD

**Issue by DerCommander323** [PrototypeTrousers/Applied-Energistics-2#95]
**Describe the bug**
When requesting an item to craft in an interface which is set to blocking mode, the world will crash.
This does result in a crash loop, however it takes a while after load to crash, so its possible to disable blocking mode on the interface and fix it.
I've checked if it was just my setup crashing, but when i tried a simple chest, it still crashes.

**To Reproduce**
1. Put pattern in interface
2. Enable blocking mode on interface
3. Request item on pattern
4. Crash

**Expected behavior**
The Item should request fine and start crafting

**Additional context**
crash log: https://gist.github.com/DerCommander323/ecb482755f7db0f79819a6929edc3d13

**Environment**
- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7-extended_life-v51e.jar
- Forge Version: 14.23.5.2860
- Singleplayer

**Comment by PrototypeTrousers** [comment]
should be fixed in v51g (when curseforge approves it ) :+1:
