### ISSUE TITLE
Add OreDict support to Charger

### ISSUE THREAD

**Issue by S1mpleM0use** [PrototypeTrousers/Applied-Energistics-2#98]
I am using GTCEu and its certus quartz isn't supported by AE2 charger. Wouldn't it be nice to have a CT method or integrated feature to accept oredict entries in charger?

Reason: for modpack makers it would open a lot of possibilities and provide convenience in making a pack.

**Comment by PrototypeTrousers** [comment]
implemented. oreDict must be the same as certus quartz crystal , "crystalCertusQuartz"
