### ISSUE TITLE
autoselect the amount of items to craft in GuiCraftAmount

### ISSUE THREAD

**Issue by k3nw4y** [PrototypeTrousers/Applied-Energistics-2#99]
**Describe the feature**

In the crafting amount window the default amount should be selected by default
![image](https://user-images.githubusercontent.com/46229190/165046157-936a21f7-25cd-4435-a613-87d5793efa67.png)

**Reasons why it should be considered**

When we select an item to craft from ME terminal, the default cursor is after the 1 which we have to clear before typing the new amount, so if we need 32 of an item we have to clear it first and then type the amount, but in latest versions of AE the amount value is selected by default, so we can just type in the amount without clearing it, its a small Qol feature lets you type the amount without having to hit backspace everytime when you need something more than 10

**Additional Context**

Can be achieved by adding `this.amountToCraft.setSelectionPos(0);` in [GuiCraftAmount.java](https://github.com/PrototypeTrousers/Applied-Energistics-2/blob/AE2-Omnifactory/src/main/java/appeng/client/gui/implementations/GuiCraftAmount.java)
Link to the PR for same in 1.7.10 fork for GTNH https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/103

**Comment by PrototypeTrousers** [comment]
should be a thing in 0.52.4
